# Generated by Django 5.0 on 2023-12-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_datta_pro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
