#### - Access Request a Token
POST https://auth.adcrws.com/api/v1/tokens
Content-Type: application/json
Accept-Type: application/json
Authorization: Bearer ca3f3acbaa6714057023aee3f5f8960eed66cfa216c5ab75afec2d7cb1679d82

{
  "first_name": "",
  "last_name": "",
  "email_address": "trin@ymail.com",
  "member_key": "VSID2",
  "scope": "travel"
}


#### - Access Request a Token
POST  https://auth.adcrws-stage.com/api/v1/tokens
Content-Type: application/json
Accept-Type: application/json
Authorization: Bearer a72968e3032dfe10e30a09b5cb70b28abbef06cb5404e2dbcfd9cc85511cea9e

{
    "member_key":"12345",
    "email":"trinthana@hotmail.com",
    "first_name":"Trin",
    "last_name":"Thana",
    "scope":"travel"    
}

