#### - Created Default Account
POST http://127.0.0.1:8000/api/CreateUser/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 856c39fd3c72a0ef5e5ccc782b8bd2386a9e7028

{
    "Email":"trinthana@hotmail.com",
    "FirstName":"Trin",
    "LastName":"Thana",
    "Address":"394",
    "City":"Bangkok",
    "StateCode":"TH",
    "CountryCode":"TH",
    "PostalCode":"TH",
    "Phone":"9999999999"
}

###################
POST http://127.0.0.1:8000/api/GenTokens/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 856c39fd3c72a0ef5e5ccc782b8bd2386a9e7028
