#### - Created Default Account
POST https://api.saveonresorts.com/v2/clubmembership/createdefault
Content-Type: application/json
Accept-Type: application/json
x-saveon-username: Vacationsavers24
x-saveon-secret: iawdygcvqmndcqjt

{
    "Email":"trinthana@hotmail.com",
    "Password":"Ultraman80",
    "FirstName":"Trin",
    "LastName":"Thana",
    "Address":"394/44",
    "City":"Bangkok",
    "TwoLetterCountryCode":"TH",
    "Phone":"9999999999",
    "ContractNumber":"TrinThana",
    "UserAccountTypeID":5,
    "ReferringUserId":""
}


### Get Login Token
POST https://api.saveonresorts.com/clubmembership/getlogintokennovalidation
Content-Type: application/json
Accept-Type: application/json

{
    "APIUsername": "Vacationsavers24", 
    "APIPassword": "iawdygcvqmndcqjt", 
    "Email": "marketing@vacationsavers.com", 
    "Password": "184922b1!A", 
    "ContractNumber": "VSmarketing@vacationsavers.com"
}

### Deactivate
POST https://api.saveonresorts.com/clubmembership/deactivatemember
Content-Type: application/json
Accept-Type: application/json

{
    "APIUsername": "Vacationsavers24", 
    "APIPassword": "iawdygcvqmndcqjt", 
    "Email": "trin@lbftravel.com", 
    "Password": "184922b1!A", 
    "ContractNumber": "VSTrin"
}

### Reactivate
POST https://api.saveonresorts.com/clubmembership/activatemember
Content-Type: application/json
Accept-Type: application/json

{
    "APIUsername": "Vacationsavers24", 
    "APIPassword": "iawdygcvqmndcqjt", 
    "Email": "trin@lbftravel.com", 
    "Password": "184922b1!A", 
    "ContractNumber": "VSTrin"
}

### Retreive all members
POST https://api.saveonresorts.com/clubmembership/getmembers
Content-Type: application/json
Accept-Type: application/json

{
    "APIUsername": "Vacationsavers24", 
    "APIPassword": "iawdygcvqmndcqjt", 
}

