# Generated by Django 5.2 on 2026-06-24 02:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, choices=[('ACCESS', 'Access Development'), ('ACCESSIFRAME', 'Access Development Iframe'), ('ACCESSDEAL', 'Access Development Deals'), ('ARRIVIA', 'Arrivia Cruise'), ('EXPEDIA', 'Expedia'), ('BOOKING', 'Booking.com'), ('BEDSOPIA', 'Bedsopia'), ('YALAGO', 'Yalago'), ('WORLDIA', 'Worldia Car'), ('CRUISEWATCH', 'Cruisewatch'), ('CRUISEDIRECT', 'CruiseDirect'), ('DREAMLINES', 'Dreamlines'), ('CARTRAWLER', 'CarTrawler'), ('TOURRADAR', 'TourRadar'), ('GETYOURGUIDE', 'GetYourGuide'), ('GADVENGER', 'G Advengers'), ('TIMETOTICKET', 'Time To Ticket'), ('TICKETNETWORK', 'Ticket Network'), ('INTERLNKD', 'InterLNKD'), ('GLOBATECH', 'GlobalTech'), ('TALIXO', 'Talixo'), ('WELCOME', 'Welcome Pick Ups'), ('TRANSFERZ', 'Transferz'), ('HOLIBOB', 'Holibob'), ('SERVANTRIP', 'Servantrip'), ('NEZASA', 'Nezasa'), ('GTN', 'GTN Vacation Rental'), ('VSFLIGHT', 'VacationSavers Flight'), ('WEBBREZ', 'Web Rez'), ('DUNHILL', 'DUNHILL Special Deals')], default='', max_length=20, null=True)),
                ('tx_date', models.DateField()),
                ('tx_counted', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('user', models.TextField(max_length=40)),
                ('tx_date', models.DateField()),
                ('tx_time', models.TimeField()),
                ('remote_addr', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('browser_family', models.TextField(blank=True, default='', null=True)),
                ('browser_version_string', models.TextField(blank=True, default='', null=True)),
                ('os_family', models.TextField(blank=True, default='', null=True)),
                ('os_version_string', models.TextField(blank=True, default='', null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_touch_capable', models.BooleanField(default=False)),
                ('is_ios', models.BooleanField(default=False)),
                ('is_android', models.BooleanField(default=False)),
                ('is_linux', models.BooleanField(default=False)),
                ('is_windows', models.BooleanField(default=False)),
                ('is_mac', models.BooleanField(default=False)),
                ('login_datetime', models.DateTimeField(null=True)),
                ('logout_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryBrowsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_date', models.DateField()),
                ('browser_family', models.TextField(blank=True, default='', null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_date', models.DateField()),
                ('desktop', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(default=0)),
                ('tablet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_date', models.DateField()),
                ('ios', models.IntegerField(default=0)),
                ('android', models.IntegerField(default=0)),
                ('linux', models.IntegerField(default=0)),
                ('windows', models.IntegerField(default=0)),
                ('mac', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, choices=[('ACCESS', 'Access Development'), ('ACCESSIFRAME', 'Access Development Iframe'), ('ACCESSDEAL', 'Access Development Deals'), ('ARRIVIA', 'Arrivia Cruise'), ('EXPEDIA', 'Expedia'), ('BOOKING', 'Booking.com'), ('BEDSOPIA', 'Bedsopia'), ('YALAGO', 'Yalago'), ('WORLDIA', 'Worldia Car'), ('CRUISEWATCH', 'Cruisewatch'), ('CRUISEDIRECT', 'CruiseDirect'), ('DREAMLINES', 'Dreamlines'), ('CARTRAWLER', 'CarTrawler'), ('TOURRADAR', 'TourRadar'), ('GETYOURGUIDE', 'GetYourGuide'), ('GADVENGER', 'G Advengers'), ('TIMETOTICKET', 'Time To Ticket'), ('TICKETNETWORK', 'Ticket Network'), ('INTERLNKD', 'InterLNKD'), ('GLOBATECH', 'GlobalTech'), ('TALIXO', 'Talixo'), ('WELCOME', 'Welcome Pick Ups'), ('TRANSFERZ', 'Transferz'), ('HOLIBOB', 'Holibob'), ('SERVANTRIP', 'Servantrip'), ('NEZASA', 'Nezasa'), ('GTN', 'GTN Vacation Rental'), ('VSFLIGHT', 'VacationSavers Flight'), ('WEBBREZ', 'Web Rez'), ('DUNHILL', 'DUNHILL Special Deals')], default='', max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=200)),
                ('custom1', models.TextField(blank=True, default='')),
                ('custom2', models.TextField(blank=True, default='')),
                ('custom3', models.TextField(blank=True, default='')),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, choices=[('FIRSTLOGIN', 'First Login'), ('WINTERSALE', 'Winter Sales'), ('SUMMERSALE', 'Summer Sales'), ('HALLOWEEN', 'Halloween Sales')], default='', max_length=10)),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_package', models.CharField(blank=True, choices=[('PREMIER', 'Premier Savings Plan'), ('ELITE', 'Elite Savings Plan'), ('ULTIMATE', 'Ultimate Savings Bundle')], default='', max_length=10)),
                ('subscribed_date', models.DateField(null=True)),
                ('expired_date', models.DateField(null=True)),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.TextField(blank=True, default='')),
                ('state_code', models.CharField(blank=True, default='', max_length=2)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('token', models.TextField(blank=True, default='')),
                ('subscribed_package', models.CharField(blank=True, choices=[('PREMIER', 'Premier Savings Plan'), ('ELITE', 'Elite Savings Plan'), ('ULTIMATE', 'Ultimate Savings Bundle')], default='', max_length=10)),
                ('subscribed_date', models.DateField(blank=True, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, choices=[('ACCESS', 'Access Development'), ('ACCESSIFRAME', 'Access Development Iframe'), ('ACCESSDEAL', 'Access Development Deals'), ('ARRIVIA', 'Arrivia Cruise'), ('EXPEDIA', 'Expedia'), ('BOOKING', 'Booking.com'), ('BEDSOPIA', 'Bedsopia'), ('YALAGO', 'Yalago'), ('WORLDIA', 'Worldia Car'), ('CRUISEWATCH', 'Cruisewatch'), ('CRUISEDIRECT', 'CruiseDirect'), ('DREAMLINES', 'Dreamlines'), ('CARTRAWLER', 'CarTrawler'), ('TOURRADAR', 'TourRadar'), ('GETYOURGUIDE', 'GetYourGuide'), ('GADVENGER', 'G Advengers'), ('TIMETOTICKET', 'Time To Ticket'), ('TICKETNETWORK', 'Ticket Network'), ('INTERLNKD', 'InterLNKD'), ('GLOBATECH', 'GlobalTech'), ('TALIXO', 'Talixo'), ('WELCOME', 'Welcome Pick Ups'), ('TRANSFERZ', 'Transferz'), ('HOLIBOB', 'Holibob'), ('SERVANTRIP', 'Servantrip'), ('NEZASA', 'Nezasa'), ('GTN', 'GTN Vacation Rental'), ('VSFLIGHT', 'VacationSavers Flight'), ('WEBBREZ', 'Web Rez'), ('DUNHILL', 'DUNHILL Special Deals')], default='', max_length=20)),
                ('tx_date', models.DateField()),
                ('tx_time', models.TimeField()),
                ('tx_url', models.TextField(blank=True, default='', null=True)),
                ('remote_host', models.TextField(blank=True, default='', null=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('http_headers', models.TextField(blank=True, default='', null=True)),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'application', 'tx_date', 'tx_time')},
            },
        ),
    ]
