# Generated by Django 4.2.7 on 2023-12-07 08:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('image', models.URLField(default='')),
                ('subscribed_package', models.CharField(blank=True, choices=[('PREMIER', 'Premier Savings Plan'), ('ELITE', 'E;ite Savings Plan'), ('ULTIMATE', 'Ultimate Savings Bundle')], default='', max_length=10)),
                ('subscribed_date', models.DateField(null=True)),
                ('expired_date', models.DateField(null=True)),
                ('updated_datetime', models.DateTimeField(default=datetime.datetime(2023, 12, 7, 8, 17, 0, 223441))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_package', models.CharField(blank=True, choices=[('PREMIER', 'Premier Savings Plan'), ('ELITE', 'E;ite Savings Plan'), ('ULTIMATE', 'Ultimate Savings Bundle')], default='', max_length=10)),
                ('subscribed_date', models.DateField(null=True)),
                ('expired_date', models.DateField(null=True)),
                ('updated_datetime', models.DateTimeField(default=datetime.datetime(2023, 12, 7, 8, 17, 0, 223928))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, choices=[('ACCESS', 'Access Development'), ('ARRIVIA', 'Arrivia'), ('EXPEDIA', 'Expedia'), ('BOOKING', 'Booking.com'), ('BEDSOPIA', 'Bedsopia'), ('YALAGO', 'Yalago'), ('WORLDIA', 'Worldia'), ('CRUISEWATCH', 'Cruisewatch'), ('CRUISEDIRECT', 'CruiseDirect'), ('DREAMLINES', 'Dreamlines'), ('CARTRAWLER', 'CarTrawler'), ('TOURRADAR', 'TourRadar'), ('GETYOURGUIDE', 'GetYourGuide'), ('GADVENGER', 'G Advengers'), ('TICKETNETWORK', 'Ticket Network'), ('INTERLNKD', 'InterLNKD'), ('GLOBATECH', 'GlobalTech'), ('TALIXO', 'Talixo'), ('WELCOME', 'Welcome Pick Ups'), ('TRANSFERZ', 'Transferz'), ('HOLIBOB', 'Holibob'), ('SERVANTRIP', 'Servantrip'), ('NEZASA', 'Nezasa')], default='', max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=50)),
                ('custom1', models.TextField(blank=True, default='')),
                ('custom2', models.TextField(blank=True, default='')),
                ('custom3', models.TextField(blank=True, default='')),
                ('updated_datetime', models.DateTimeField(default=datetime.datetime(2023, 12, 7, 8, 17, 0, 223709))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
