# Generated by Django 4.2.7 on 2023-12-07 08:20

import datetime
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_applicationtoken_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='updated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 8, 20, 23, 481393)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 8, 20, 23, 480934)),
        ),
    ]
