# Generated by Django 4.2.7 on 2023-12-07 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_applicationtoken_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 8, 25, 8, 970659)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 8, 25, 8, 970176)),
        ),
    ]
