# Generated by Django 4.2.7 on 2023-12-10 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_subscriptionhistory_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 11, 18, 56, 398972)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscribed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 11, 18, 56, 398490)),
        ),
    ]
