# Generated by Django 4.2.7 on 2023-12-10 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_subscriptionhistory_updated_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 23, 17, 59, 839088)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 23, 17, 59, 838526)),
        ),
    ]
