# Generated by Django 4.2.7 on 2023-12-11 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_applicationtoken_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 0, 51, 20, 563423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 0, 51, 20, 563643, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 0, 51, 20, 562806, tzinfo=datetime.timezone.utc)),
        ),
    ]
