# Generated by Django 5.0 on 2023-12-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_applicationtoken_updated_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
