# Generated by Django 5.0 on 2024-01-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
