# Generated by Django 5.0 on 2024-01-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
