# Generated by Django 5.0 on 2024-01-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='application',
            field=models.CharField(blank=True, choices=[('ACCESS', 'Access Development'), ('ACCESSDEAL', 'Access Development Deals'), ('ARRIVIA', 'Arrivia'), ('EXPEDIA', 'Expedia'), ('BOOKING', 'Booking.com'), ('BEDSOPIA', 'Bedsopia'), ('YALAGO', 'Yalago'), ('WORLDIA', 'Worldia'), ('CRUISEWATCH', 'Cruisewatch'), ('CRUISEDIRECT', 'CruiseDirect'), ('DREAMLINES', 'Dreamlines'), ('CARTRAWLER', 'CarTrawler'), ('TOURRADAR', 'TourRadar'), ('GETYOURGUIDE', 'GetYourGuide'), ('GADVENGER', 'G Advengers'), ('TICKETNETWORK', 'Ticket Network'), ('INTERLNKD', 'InterLNKD'), ('GLOBATECH', 'GlobalTech'), ('TALIXO', 'Talixo'), ('WELCOME', 'Welcome Pick Ups'), ('TRANSFERZ', 'Transferz'), ('HOLIBOB', 'Holibob'), ('SERVANTRIP', 'Servantrip'), ('NEZASA', 'Nezasa')], default='', max_length=20),
        ),
    ]
