# Generated by Django 5.0 on 2024-02-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_applicationtoken_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='application',
            field=models.CharField(blank=True, choices=[('ACCESS', 'Access Development'), ('ACCESSIFRAME', 'Access Development Iframe'), ('ACCESSDEAL', 'Access Development Deals'), ('ARRIVIA', 'Arrivia'), ('EXPEDIA', 'Expedia'), ('BOOKING', 'Booking.com'), ('BEDSOPIA', 'Bedsopia'), ('YALAGO', 'Yalago'), ('WORLDIA', 'Worldia'), ('CRUISEWATCH', 'Cruisewatch'), ('CRUISEDIRECT', 'CruiseDirect'), ('DREAMLINES', 'Dreamlines'), ('CARTRAWLER', 'CarTrawler'), ('TOURRADAR', 'TourRadar'), ('GETYOURGUIDE', 'GetYourGuide'), ('GADVENGER', 'G Advengers'), ('TICKETNETWORK', 'Ticket Network'), ('INTERLNKD', 'InterLNKD'), ('GLOBATECH', 'GlobalTech'), ('TALIXO', 'Talixo'), ('WELCOME', 'Welcome Pick Ups'), ('TRANSFERZ', 'Transferz'), ('HOLIBOB', 'Holibob'), ('SERVANTRIP', 'Servantrip'), ('NEZASA', 'Nezasa')], default='', max_length=20),
        ),
    ]
