# Generated by Django 5.0 on 2024-02-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_clicksummary_clickdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickdetails',
            old_name='remote_address',
            new_name='remote_addr',
        ),
    ]
