# Generated by Django 5.0 on 2024-02-21 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_remote_address_clickdetails_remote_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickdetails',
            name='tx_date',
            field=models.DateField(default=datetime.date(2024, 2, 21)),
        ),
        migrations.AlterField(
            model_name='clickdetails',
            name='tx_time',
            field=models.TimeField(default=datetime.time(14, 37, 9, 444749)),
        ),
        migrations.AlterField(
            model_name='clickdetails',
            name='tx_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='clicksummary',
            name='tx_date',
            field=models.DateField(default=datetime.date(2024, 2, 21)),
        ),
    ]
