# Generated by Django 5.0 on 2024-02-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_clickdetails_tx_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='os_version',
        ),
    ]
