# Generated by Django 5.0 on 2024-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_sessions_browser_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='user',
            field=models.TextField(max_length=40),
        ),
    ] 
