# Generated by Django 5.0 on 2024-02-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_sessions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='remote_addr',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ] 
