# Generated by Django 5.0 on 2024-02-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_sessions_remote_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryBrowsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_date', models.DateField()),
                ('browser_family', models.TextField(blank=True, default='', null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_date', models.DateField()),
                ('desktop', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(default=0)),
                ('tablet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_date', models.DateField()),
                ('ios', models.IntegerField(default=0)),
                ('android', models.IntegerField(default=0)),
                ('linux', models.IntegerField(default=0)),
                ('windows', models.IntegerField(default=0)),
                ('mac', models.IntegerField(default=0)),
            ],
        ),
    ] 
