# Generated by Django 5.0.2 on 2024-02-28 02:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_summarybrowsers_summarydevices_summaryos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, choices=[('FIRSTLOGIN', 'First Login'), ('WINTERSALE', 'Winter Sales'), ('SUMMERSALE', 'Summer Sales'), ('HALLOWEEN', 'Halloween Sales')], default='', max_length=10)),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ] 
