#### - Created Default Account
POST http://127.0.0.1:8000/api/CreateUser/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 856c39fd3c72a0ef5e5ccc782b8bd2386a9e7028

{
    "username":"TrinLBF10",
    "email":"trin@LBFTravel.com",
    "first_name":"Trin",
    "last_name":"Thana",
    "address":"394",
    "city":"Bangkok",
    "state_code":"",
    "country_code":"TH",
    "postal_code":"92123",
    "phone":"9999999999"
}

###################
POST http://127.0.0.1:8000/api/GetAuthToken/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 856c39fd3c72a0ef5e5ccc782b8bd2386a9e7028

{
    "username":"TinTin"
}

###################
POST http://127.0.0.1:8000/api/DeactivateUser/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 856c39fd3c72a0ef5e5ccc782b8bd2386a9e7028

{
    "username":"TinTin"
}

###################
POST http://127.0.0.1:8000/api/ReActivateUser/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 856c39fd3c72a0ef5e5ccc782b8bd2386a9e7028

{
    "username":"TinTin"
}

###################
POST http://127.0.0.1:8000/api/GetUserList/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 856c39fd3c72a0ef5e5ccc782b8bd2386a9e7028


###################
POST http://127.0.0.1:8000/api/subscribe/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 856c39fd3c72a0ef5e5ccc782b8bd2386a9e7028

{
  "first_name": "Trin",
  "last_name": "Thana",
  "email": "trin@lbftravel.com",
  "username": "TrinLBF05",
  "address": "XXX",
  "city": "XXX",
  "state_code": "XX",
  "postal_code": "99999",
  "country_code": "US",
  "phone": "123456789",
  "addon_code": "STARTREK",
  "subscribed_date": "2025-05-16",
  "phone_country": "66",
  "phone_area": "89",
  "phone_number": "9999999",
  "cc_number": "1111111111111111",
  "cc_exp": "11/31",
  "cc_cvv": "234",
  "locator": "LOCATOR"
}


###################
GET https://www.vacationsavers.com/api/GenTokens/?number=1
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 85abc4a2e156c311d027f9f3af06f34c1ac1de58

###################
GET https://www.vacationsavers.com/api/GetUserList/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 87beeb0fc2990a8c08a960172aec299f951e0808

###################
POST https://www.vacationsavers.com/api/GetUserList/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 85abc4a2e156c311d027f9f3af06f34c1ac1de58


#### - Created Default Account
POST https://www.vacationsavers.com/api/CreateUser/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 85abc4a2e156c311d027f9f3af06f34c1ac1de58

{
    "username":"TrinLBF9",
    "email":"trin@LBFTravel.com",
    "first_name":"Trin",
    "last_name":"Thana",
    "address":"394",
    "city":"Bangkok",
    "state_code":"",
    "country_code":"TH",
    "postal_code":"92123",
    "phone":"9999999999"
}

###################
POST https://www.vacationsavers.com/api/subscribe/
Content-Type: application/json
Accept-Type: application/json
Authorization: Token 87beeb0fc2990a8c08a960172aec299f951e0808

{
  "first_name": "Doug",
  "last_name": "Martin",
  "email": "doug@militaryfares.com",
  "username": "DougMF",
  "address": "XXX",
  "city": "XXX",
  "state_code": "XX",
  "postal_code": "99999",
  "country_code": "US",
  "phone": "123456789",
  "addon_code": "STARTREK",
  "subscribed_date": "2025-06-10",
  "phone_country": "66",
  "phone_area": "89",
  "phone_number": "9999999",
  "cc_number": "1111111111111111",
  "cc_exp": "11/31",
  "cc_cvv": "234",
  "locator": "LOCATOR"
}

#### - Send EMail
POST https://edapi.campaigner.com/v1/RelaySends/11290
Content-Type: application/json
ApiKey: 8831bdf3-663b-4692-80ab-fb1729ddce57

{
  "ToEmail": "trinthana@hotmail.com",
  "Subject": "Simple Email Example",
  "HTML": "Hello Relay Send World"
}


#### -Create SENDCATEGORY
POST https://edapi.campaigner.com/v1/RelaySends
Content-Type: application/json
ApiKey: 8831bdf3-663b-4692-80ab-fb1729ddce57

"VacationSavers Profile Change"

#Integration Keys ccba7a68-6909-4cf0-ba61-55287bb1f713

#### - Query SMTP SENDCATEGORY
GET https://edapi.campaigner.com/v1/RelaySends
Content-Type: application/json
ApiKey: 8831bdf3-663b-4692-80ab-fb1729ddce57